DROP INDEX IF EXISTS idx_kosts_province;
DROP INDEX IF EXISTS idx_kosts_postal;
ALTER TABLE kosts DROP COLUMN IF EXISTS province;
ALTER TABLE kosts DROP COLUMN IF EXISTS regency;
ALTER TABLE kosts DROP COLUMN IF EXISTS district;
ALTER TABLE kosts DROP COLUMN IF EXISTS village;
ALTER TABLE kosts DROP COLUMN IF EXISTS postal_code;
